### ISSUE TITLE
p2p review - 3 Feb 2020

### ISSUE THREAD

**Issue by Kyle-Law** [Kyle-Law/Online-Shop-for-Electronics#2]
Feel free to leave any comments or suggestions :)

**Comment by patriciachrysy** [comment]
Good Job as always Kyle. Did not go into the code because of time so I just have few remarks about the design reproduction:
- You may check the background color again. Apart from the header, the rest of the page must have a grey background
- Check the text colors and sizes again and compare them to the design
- Normally the page is supposed to be full-sized with no left or right space like on the design
- On the mobile version, the header is supposed to change the appearance and the products must be displayed two per line
These are just a few remarks I have.
Anyway, good job as usual

**Comment by dili021** [comment]
+1 @patriciachrysy 
Looking good though, good work!

**Comment by nyatindopatrick** [comment]
Good work!
